name: serp_notification_service
description: api package
homepage: https://s-erp.vn
# publish_to: 'https://pub.dev' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
versionCode: 1

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  chopper: ^4.0.5
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  collection: ^1.16.0
  
dev_dependencies:
  swagger_dart_code_generator: ^2.5.4+1
  chopper_generator: ^4.0.5
  build_runner: ^2.1.11
  lints: ^2.0.0