name: serp_http_service
description: api package
homepage: https://s-erp.vn
# publish_to: 'https://pub.dev' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
versionCode: 1

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  connectivity_plus: ^2.3.0
  dio: ^4.0.6
  hive: ^2.2.1
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.10
  
dev_dependencies: 
  lints: ^2.0.0